### ISSUE TITLE
请问下 为什么生成出来的二维码跳转的网站都是大写的

### ISSUE THREAD

**Issue by awei84** [soulteary/nginx-qrcode-server#1]
使用的[docker](nginx-qrcode-server:release-2021.01.06)
http://127.0.0.1:8080/?txt=http://abc.club/?rid=RJBE4tl
生成的二维码跳转的地址为
http://abc.club/?RID=RJBE4tl
大佬能帮我解答下疑问吗

**Comment by awei84** [comment]
容器为 nginx-qrcode-server:release-2021.01.06

**Comment by awei84** [comment]
找到原因了 修改case参数即可
请问下大佬，您后面更新的版本跟2021.1这个docker镜像做了什么更新吗？

**Comment by soulteary** [comment]
https://github.com/soulteary/nginx-qrcode-server/compare/2021.01.06...2022.08.22

@awei84 可以参考提交记录 :)
